<div class="outerbox span3 color-1" onclick="toggle_box('{{ id }}')" id="{{ id }}">
  <div class="box border border-{{ state }}">
    <i class="color-{{ state }} {{ icon }}"></i>
    <h2>{{ title }}</h2>
    <p>{{ text }}</p>
    <div class="hidden">
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec
      semper nibh fermentum facilisis placerat. Cras rhoncus nisl ut
      felis placerat faucibus. Aliquam erat volutpat. Vivamus sed
      lobortis velit. Nulla a aliquam libero. In urna nibh, dapibus et
      auctor sed, gravida ut nisi. Nullam posuere, magna vitae
      vestibulum lacinia, velit ipsum sollicitudin nisi, eu varius
      elit sapien vitae sapien. Nullam dui metus, euismod in enim in,
      ultrices tempus tortor. Donec hendrerit accumsan erat, id
      porttitor sapien malesuada vel. Praesent magna neque, lobortis
      ac accumsan a, accumsan at nunc.
    </div>

  </div>
</div>
