#!/usr/bin/python
# -*- coding: utf-8 -*-
"""Checks problems on the AMT railways (Montreal).
"""
#
#
#     Copyright (C) 2012 Savoir-Faire Linux Inc.
#
#     This program is free software; you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation; either version 3 of the License, or
#     (at your option) any later version.
#
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program; if not, write to the Free Software
#     Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
#     Projects :
#               SFL Shinken plugins
#
#     File :
#               check_amt.py Checks problems on the AMT railways (Montreal).
#
#
#     Author: Matthieu Caneill <matthieu.caneill@savoirfairelinux.com>
#
#

# Generated with tools/create_new_plugin.sh

import getopt
import sys

import urllib2
import gtfs_realtime_pb2 as gtfs

PLUGIN_NAME = "check_amt"
PLUGIN_VERSION = "0.1"
STATE_OK = 0
STATE_WARNING = 1
STATE_CRITICAL = 2
STATE_UNKNOWN = 3
STATE_DEPENDENT = 4


def print_version():
    """Show plugin version
    """
    version_msg = """
%s.py v%s (sfl-shinken-plugins)

The SFL Shinken Plugins come with ABSOLUTELY NO WARRANTY. You may redistribute
copies of the plugins under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
""" % (PLUGIN_NAME, PLUGIN_VERSION)
    print version_msg


def print_support():
    """Show plugin support
    """
    support_msg = """
Send email to <matthieu.caneill@savoirfairelinux.com> if you have questions
regarding use of this software. To submit patches or suggest improvements,
send email to <matthieu.caneill@savoirfairelinux.com>
Please include version information with all correspondence (when
possible, use output from the --version option of the plugin itself).
"""
    print support_msg


def print_usage():
    """Show how to use this plugin
    """
    usage_msg = """
%s.py -U <url> -t <token> -w <warning> -c <critical>

Usage:
 -h, --help
    Print detailed help screen
 -U, --url=ADDRESS
    URL of the data to retrieve
 -t, --token=TOKEN
    Your personal token provided by AMT
 -V, --version
    Print version information
 -w, --warning=DOUBLE
    Response time to result in warning status (seconds)
 -c, --critical=DOUBLE
    Response time to result in critical status (seconds)
""" % PLUGIN_NAME
    print usage_msg

def get_feed(url):
    try:
        feed = urllib2.urlopen(url)
    except Exception as e:
        print('Error while opening url: %s' % str(e))
        sys.exit(STATE_UNKNOWN)
    if feed.getcode() >= 400:
        print('HTTP error: %d' % feed.getcode())
        sys.exit(STATE_UNKNOWN)
    return feed.read()


def get_data(args):
    """Fetch data
    """
    url = args['url'] + '?token=' + args['token']
    data = get_feed(url)

    alerts = gtfs.FeedMessage()
    try:
        alerts.ParseFromString(data)
    except Exception as e:
        print('Bad data format or unknown error: %s' % e)
        sys.exit(STATE_UNKNOWN)
    
    nb = len(alerts.entity)
    str_plural = 'problems' if nb >= 2 else 'problem'

    perfdata = ('problems=%(problems)d;%(warning)d;%(critic)d;0;'
                % {'problems': nb,
                   'warning': int(args['warning']),
                   'critic': int(args['critical']),
                  })
    
    if nb < int(args['warning']):
        print('OK - %d %s|%s' % (nb, str_plural, perfdata))
        sys.exit(STATE_OK)
    elif nb < int(args['critical']):
        print('WARNING - %d %s|%s' % (nb, str_plural, perfdata))
        sys.exit(STATE_WARNING)
    else:
        print('CRITICAL - %d %s|%s' % (nb, str_plural, perfdata))
        sys.exit(STATE_CRITICAL)

def check_arguments(args):
    """Check mandatory fields
    """
    mandatory_arguments = ['url', 'token',
                           'warning', 'critical']
    for argument_name in mandatory_arguments:
        if not argument_name in args.keys():
            print "Argument '%s' is missing !" % argument_name
            print_usage()
            print_support()
            sys.exit(STATE_UNKNOWN)


def main():
    """Main function
    """
    try:
        options, args = getopt.getopt(sys.argv[1:],
                        'U:t:hVw:c:',
                        ['url=', 'token=', 'help', 'version',
                         'warning=', 'critical='])
    except getopt.GetoptError, err:
        print str(err)
        print_usage()
        sys.exit(STATE_UNKNOWN)

    args = {}

    for option_name, value in options:
        if option_name in ("-U", "--url"):
            args['url'] = value
        elif option_name in ("-t", "--token"):
            args['token'] = value
        elif option_name in ("-w", "--warning"):
            args['warning'] = value
        elif option_name in ("-c", "--critical"):
            args['critical'] = value
        elif option_name in ("-h", "--help"):
            print_version()
            print_usage()
            print_support()
            sys.exit(STATE_UNKNOWN)
        elif option_name in ("-V", "--version"):
            print_version()
            print_support()
            sys.exit(STATE_UNKNOWN)

    check_arguments(args)

    get_data(args)


if __name__ == "__main__":
    main()
