#!/usr/bin/python
# -*- coding: utf-8 -*-
"""Checks HTTP sites, and doesn't timeout like good'old check_http.
"""
#
#
#     Copyright (C) 2012 Savoir-Faire Linux Inc.
#
#     This program is free software; you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation; either version 3 of the License, or
#     (at your option) any later version.
#
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program; if not, write to the Free Software
#     Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
#     Projects :
#               SFL Shinken plugins
#
#     File :
#               check_http2.py Checks HTTP sites, and doesn't timeout like good'old check_http.
#
#
#     Author: Matthieu Caneill <matthieu.caneill@savoirfairelinux.com>
#
#

# Generated with tools/create_new_plugin.sh

import getopt
import sys

import urllib2

PLUGIN_NAME = "check_http2"
PLUGIN_VERSION = "0.1"
STATE_OK = 0
STATE_WARNING = 1
STATE_CRITICAL = 2
STATE_UNKNOWN = 3
STATE_DEPENDENT = 4


def print_version():
    """Show plugin version
    """
    version_msg = """
%s.py v%s (sfl-shinken-plugins)

The SFL Shinken Plugins come with ABSOLUTELY NO WARRANTY. You may redistribute
copies of the plugins under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
""" % (PLUGIN_NAME, PLUGIN_VERSION)
    print version_msg


def print_support():
    """Show plugin support
    """
    support_msg = """
Send email to <matthieu.caneill@savoirfairelinux.com> if you have questions
regarding use of this software. To submit patches or suggest improvements,
send email to <matthieu.caneill@savoirfairelinux.com>
Please include version information with all correspondence (when
possible, use output from the --version option of the plugin itself).
"""
    print support_msg


def print_usage():
    """Show how to use this plugin
    """
    usage_msg = """
%s.py -U <url>

Usage:
 -h, --help
    Print detailed help screen
 -U, --url=ADDRESS
    URL
 -A, --user-agent=STR
    User-Agent header
 -V, --version
    Print version information
""" % PLUGIN_NAME
    print usage_msg


def get_data(args):
    """Fetch data
    """
    url = args['url']
    
    try:
        request = urllib2.Request(url)
        opener = urllib2.build_opener()
        if args.get('user-agent'):
            request.add_header('User-Agent', args['user-agent'])
            
        code = opener.open(request).getcode()
    except Exception as e:
        try:
            code = e.code
            print 'CRITICAL - HTTP %s - %s' % (code, e)
            sys.exit(STATE_CRITICAL)

        except Exception:
            print 'UNKNOWN - %s' % e
            sys.exit(STATE_UNKNOWN)
    
    if code < 400:
        print 'OK - HTTP %s' % code
        sys.exit(STATE_OK)
    else:
        print 'CRITICAL - HTTP %s' % code
        sys.exit(STATE_CRITICAL)

def check_arguments(args):
    """Check mandatory fields
    """
    mandatory_arguments = ['url']
    
    for argument_name in mandatory_arguments:
        if not argument_name in args.keys():
            print "Argument '%s' is missing !" % argument_name
            print_usage()
            print_support()
            sys.exit(STATE_UNKNOWN)

def main():
    """Main function
    """
    try:
        options, args = getopt.getopt(sys.argv[1:],
                        'A:U:hV',
                        ['hostname=', 'help', 'version'])
    except getopt.GetoptError, err:
        print str(err)
        print_usage()
        sys.exit(STATE_UNKNOWN)

    args = {}

    for option_name, value in options:
        if option_name in ("-U", "--url"):
            args['url'] = value
        elif option_name in ("-A", "--user-agent"):
            args['user-agent'] = value
        elif option_name in ("-h", "--help"):
            print_version()
            print_usage()
            print_support()
            sys.exit(STATE_UNKNOWN)
        elif option_name in ("-V", "--version"):
            print_version()
            print_support()
            sys.exit(STATE_UNKNOWN)

    check_arguments(args)

    get_data(args)


if __name__ == "__main__":
    main()
