#!/usr/bin/python
# -*- coding: utf-8 -*-
"""Checks the occupation of emergency rooms in Québec.
"""
#
#
#     Copyright (C) 2012 Savoir-Faire Linux Inc.
#
#     This program is free software; you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation; either version 3 of the License, or
#     (at your option) any later version.
#
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program; if not, write to the Free Software
#     Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
#     Projects :
#               SFL Shinken plugins
#
#     File :
#               check_emergency_occupation.py Checks the occupation of emergency rooms in Québec.
#
#
#     Author: Matthieu Caneill <matthieu.caneill@savoirfairelinux.com>
#
#

# Generated with tools/create_new_plugin.sh

import getopt
import sys

import re
import urllib2
import lxml.html

PLUGIN_NAME = "check_emergency_occupation"
PLUGIN_VERSION = "0.1"
STATE_OK = 0
STATE_WARNING = 1
STATE_CRITICAL = 2
STATE_UNKNOWN = 3
STATE_DEPENDENT = 4


def print_version():
    """Show plugin version
    """
    version_msg = """
%s.py v%s (sfl-shinken-plugins)

The SFL Shinken Plugins come with ABSOLUTELY NO WARRANTY. You may redistribute
copies of the plugins under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
""" % (PLUGIN_NAME, PLUGIN_VERSION)
    print version_msg


def print_support():
    """Show plugin support
    """
    support_msg = """
Send email to <matthieu.caneill@savoirfairelinux.com> if you have questions
regarding use of this software. To submit patches or suggest improvements,
send email to <matthieu.caneill@savoirfairelinux.com>
Please include version information with all correspondence (when
possible, use output from the --version option of the plugin itself).
"""
    print support_msg


def print_usage():
    """Show how to use this plugin
    """
    usage_msg = """
%s.py -U <url> -w <warning> -c <critical> -f <functional_stretches> -o <occupied_stretchers>

Usage:
 -h, --help
    Print detailed help screen
 -U, --url=ADDRESS
    URL where to fetch data from
 -V, --version
    Print version information
 -w, --warning=DOUBLE
    Response time to result in warning status (seconds)
 -c, --critical=DOUBLE
    Response time to result in critical status (seconds)
 -f, --functional_stretchers=XPATH
    XPATH to the functional stretchers value
 -o, --occupied_stretchers=XPATH
    XPATH to the occupied stretchers value

""" % PLUGIN_NAME
    print usage_msg

def get_html(url):
    try:
        html = urllib2.urlopen(url)
    except Exception as e:
        print('Error while opening url: %s' % str(e))
        sys.exit(STATE_UNKNOWN)
    if html.getcode() >= 400:
        print('HTTP error: %d' % html.getcode())
        sys.exit(STATE_UNKNOWN)
    return html.read()

def get_data(args):
    """Fetch data
    """
    html = get_html(args['url'])
    tree = lxml.html.fromstring(html)
    data1 = tree.xpath(args['functional_stretchers'])
    data2 = tree.xpath(args['occupied_stretchers'])
    
    if len(data1) == len(data2) == 1:
        try:
            data1 = int(data1[0].strip())
            data2 = int(data2[0].strip())
        except Exception as e:
            print('Not integers: %s - %s' % (data1, data2))
            sys.exit(STATE_UNKNOWN)
        result = 100 * data2 / data1

        if result < int(args['warning']):
            print('OK - %d%% (%d / %d)' % (result, data2, data2))
            sys.exit(STATE_OK)
        elif result < int(args['critical']):
            print('WARNING - %d%% (%d / %d)' % (result, data2, data1))
            sys.exit(STATE_WARNING)
        else:
            print('CRITICAL - %d%% (%d / %d)' % (result, data2, data1))
            sys.exit(STATE_CRITICAL)
    
    print('Wrong data extracted: %s - %s' % (data1, data2))
    sys.exit(STATE_UNKNOWN)

def check_arguments(args):
    """Check mandatory fields
    """
    mandatory_arguments = ['url',
                           'warning',
                           'critical',
                           'functional_stretchers',
                           'occupied_stretchers']
    for argument_name in mandatory_arguments:
        if not argument_name in args.keys():
            print "Argument '%s' is missing !" % argument_name
            print_usage()
            print_support()
            sys.exit(STATE_UNKNOWN)

def main():
    """Main function
    """
    try:
        options, args = getopt.getopt(sys.argv[1:],
                            'U:hVw:c:f:o:',
                            ['url=', 'help', 'version',
                            'warning=', 'critical=',
                            'functional_stretchers=', 'occupied_stretchers='])
    except getopt.GetoptError, err:
        print str(err)
        print_usage()
        sys.exit(STATE_UNKNOWN)

    args = {}

    for option_name, value in options:
        if option_name in ("-U", "--url"):
            args['url'] = value
        elif option_name in ("-w", "--warning"):
            args['warning'] = value
        elif option_name in ("-c", "--critical"):
            args['critical'] = value
        elif option_name in ("-f", "--functional_stretchers"):
            args['functional_stretchers'] = value
        elif option_name in ("-o", "--occupied_stretchers"):
            args['occupied_stretchers'] = value
        elif option_name in ("-h", "--help"):
            print_version()
            print_usage()
            print_support()
            sys.exit(STATE_UNKNOWN)
        elif option_name in ("-V", "--version"):
            print_version()
            print_support()
            sys.exit(STATE_UNKNOWN)

    check_arguments(args)

    get_data(args)


if __name__ == "__main__":
    main()
